### ISSUE TITLE
Not being able to compile fn-fx

### ISSUE THREAD

**Issue by jpmonettas** [halgari/fn-fx#18]
Maybe there is something wrong with my system by I'm not being able to use 0.2.0 or 0.3.0-SNAPSHOT.

Current system:

```
Leiningen 2.7.1 on Java 1.8.0_11 Java HotSpot(TM) 64-Bit Server VM
```

The first problem I was facing was compiling fn-fx.util.reflect-utils
Trying to def all-javafx-types it complains in the first line that it can't initialize `javafx.stage.Screen` in current thread, only in event thread.

To avoid initializing that class I changed 

```clojure
#(Class/forName %)
```

to

```clojure
#(Class/forName % false (.getContextClassLoader (Thread/currentThread)))
```

so it doesn't try to initialize the class now, just loads it.

Now that part works but I get 

```
Error compiling fn_fx/controls.clj at (27:3)
Caused by java.lang.ClassNotFoundException
   javafx.util.converter.LocalDateTimeStringConverter
```

Any ideas of what I'm doing wrong?

**Comment by pmonks** [comment]
Just out of interest, are you using `lein check` to compile the code?

If so, I'm seeing a different (though possibly related) problem:
```
$ lein check
Compiling namespace fn-fx.util.reflect-utils
Compiling namespace fn-fx.util.filegen
Compiling namespace fn-fx.util.method-arg-indexer
Reflection warning, fn_fx/util/method_arg_indexer.clj:42:28 - call to java.io.FileInputStream ctor can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:51:33 - reference to field getName can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:52:33 - reference to field getName on java.lang.Object can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:54:48 - reference to field getName on java.lang.Object can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:55:67 - reference to field getType on java.lang.Object can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:54:48 - reference to field getName can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:55:67 - reference to field getType can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:53:45 - reference to field getParameters on java.lang.Object can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:51:33 - reference to field getName can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:52:33 - reference to field getName can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:54:48 - reference to field getName on java.lang.Object can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:55:67 - reference to field getType on java.lang.Object can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:54:48 - reference to field getName can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:55:67 - reference to field getType can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:53:45 - reference to field getParameters can't be resolved.
Reflection warning, fn_fx/util/method_arg_indexer.clj:47:30 - reference to field getMembers can't be resolved.
Compiling namespace fn-fx.render-core
Compiling namespace fn-fx.controls
Compiling namespace fn-fx.util
Compiling namespace fn-fx.render
Compiling namespace fn-fx.fx-dom
Compiling namespace fn-fx.fx-tree-search
Compiling namespace fn-fx.set-once-type
Compiling namespace fn-fx.fx-clj-gen
Reflection warning, fn_fx/fx_clj_gen.clj:42:15 - reference to field isEnum can't be resolved.
Reflection warning, fn_fx/fx_clj_gen.clj:41:30 - reference to field getName can't be resolved.
Reflection warning, fn_fx/fx_clj_gen.clj:40:30 - reference to field getName can't be resolved.
Compiling namespace fn-fx.diff
Compiling namespace fn-fx.interop-controls
Reflection warning, fn_fx/interop_controls.clj:20:13 - call to method updateItem can't be resolved (target class is unknown).
Reflection warning, fn_fx/interop_controls.clj:22:19 - call to method setGraphic can't be resolved (target class is unknown).
Reflection warning, fn_fx/interop_controls.clj:23:19 - call to method setText can't be resolved (target class is unknown).
Reflection warning, fn_fx/interop_controls.clj:24:15 - call to method setGraphic can't be resolved (target class is unknown).
Compiling namespace other-examples.shapes-3d
Compiling namespace other-examples.todo
Compiling namespace getting-started.01-hello-word
Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :create-component! of protocol: #'fn-fx.diff/IDom found for class: fn_fx.fx_dom.FXDom, compiling:(getting_started/01_hello_word.clj:25:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval149$fn__160.invoke(form-init4956059431223428853.clj:1)
	at user$eval149.invokeStatic(form-init4956059431223428853.clj:1)
	at user$eval149.invoke(form-init4956059431223428853.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No implementation of method: :create-component! of protocol: #'fn-fx.diff/IDom found for class: fn_fx.fx_dom.FXDom
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at fn_fx.diff$eval4256$fn__4329$G__4237__4336.invoke(diff.clj:7)
	at fn_fx.diff$diff$new_node__4553.invoke(diff.clj:95)
	at fn_fx.diff$diff.invokeStatic(diff.clj:99)
	at fn_fx.diff$diff.invoke(diff.clj:88)
	at fn_fx.fx_dom$app.invokeStatic(fx_dom.clj:57)
	at fn_fx.fx_dom$app.invoke(fx_dom.clj:52)
	at getting_started.01_hello_word$_main.invokeStatic(01_hello_word.clj:22)
	at getting_started.01_hello_word$_main.invoke(01_hello_word.clj:8)
	at getting_started.01_hello_word$eval4777.invokeStatic(01_hello_word.clj:25)
	at getting_started.01_hello_word$eval4777.invoke(01_hello_word.clj:25)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 26 more
Failed.
```

No clue what the issue is - I'm still a JavaFX / OpenJFX n00b, so not clear on the correct way to initialise the system.
